### ISSUE TITLE
Running transposome with contigs instead of reads

### ISSUE THREAD

**Issue by tlorin** [sestaton/Transposome#31]
Hello,

Just out of curiosity, is it possible to run Transposome with contigs instead of reads (I have a draft version of a genome)? Would you recommend it? If yes, do I just have to change the input file to my contig-based genome assembly?

Thanks a lot for your answer, 

Thibault

**Comment by sestaton** [comment]
I do not recommend running Transposome with an assembled genome. It is better to use structure-based programs for that purpose. A draft genome is typically missing a large fraction of the repetitive regions and this is one reason to use Transposome because the unassembled reads bypass the artifacts created by the assembly process. I think the result would likely be an underestimate of the true repeat abundance in the genome. You can still run Transposome as long as you have access to the raw reads.

I'll close this issue since the answer is straightforward, but I am going to release another program soon that is designed for working with assembled genomes and I'll update this issue when that program is released.

**Comment by tlorin** [comment]
Ok, thanks for your answer, and looking forward to this new program! :)
